# Оценка набора макроэкономических показателей, по одному на каждую дату. Вычислить ошибку предсказания по всему тестовому набору данных

## Выполнил студент группы М-20-ИВТ 3 
## Цыганов Никита Дмитриевич
## Вариант 3

In [ ]:
import pandas as pd
data = pd.read_csv("/content/train.csv")

In [ ]:
data

          id   timestamp  ...  market_count_5000  price_doc
0          1  2011-08-20  ...                  4    5850000
1          2  2011-08-23  ...                 14    6000000
2          3  2011-08-27  ...                 10    5700000
3          4  2011-09-01  ...                  3   13100000
4          5  2011-09-05  ...                 14   16331452
...      ...         ...  ...                ...        ...
30466  30469  2015-06-30  ...                  6    7400000
30467  30470  2015-06-30  ...                 15   25000000
30468  30471  2015-06-30  ...                  1    6970959
30469  30472  2015-06-30  ...                  7   13500000
30470  30473  2015-06-30  ...                 10    5600000

[30471 rows x 292 columns]

In [ ]:
data = data.drop(columns=['id'])
data = data.drop(columns=['timestamp'])
data

       full_sq  life_sq  floor  ...  sport_count_5000  market_count_5000  price_doc
0           43     27.0    4.0  ...                52                  4    5850000
1           34     19.0    3.0  ...                66                 14    6000000
2           43     29.0    2.0  ...                67                 10    5700000
3           89     50.0    9.0  ...                26                  3   13100000
4           77     77.0    4.0  ...               195                 14   16331452
...        ...      ...    ...  ...               ...                ...        ...
30466       44     27.0    7.0  ...                84                  6    7400000
30467       86     59.0    3.0  ...               171                 15   25000000
30468       45      NaN   10.0  ...                11                  1    6970959
30469       64     32.0    5.0  ...                65                  7   13500000
30470       43     28.0    1.0  ...                54                 10    5600000

[30471 rows x 290 columns]

In [ ]:
# Удаление строк с NAN-значениями
data = data.dropna()
data

       full_sq  life_sq  floor  ...  sport_count_5000  market_count_5000  price_doc
8056        11     11.0    2.0  ...               161                 10    2750000
8154        45     27.0    6.0  ...                19                  3    7100000
8287        77     50.0    3.0  ...               146                 12   11700000
8387        56     29.0    5.0  ...               121                  7   10400000
8391        31     21.0    5.0  ...                93                  5    6200000
...        ...      ...    ...  ...               ...                ...        ...
30462       47     30.0   23.0  ...               123                  7   10544070
30463       56     29.0   13.0  ...                53                  6   12000000
30467       86     59.0    3.0  ...               171                 15   25000000
30469       64     32.0    5.0  ...                65                  7   13500000
30470       43     28.0    1.0  ...                54                 10    5600000

[6042 rows x 290 columns]

In [ ]:
cols = data.columns.tolist()
cols

['full_sq',
 'life_sq',
 'floor',
 'max_floor',
 'material',
 'build_year',
 'num_room',
 'kitch_sq',
 'state',
 'product_type',
 'sub_area',
 'area_m',
 'raion_popul',
 'green_zone_part',
 'indust_part',
 'children_preschool',
 'preschool_quota',
 'preschool_education_centers_raion',
 'children_school',
 'school_quota',
 'school_education_centers_raion',
 'school_education_centers_top_20_raion',
 'hospital_beds_raion',
 'healthcare_centers_raion',
 'university_top_20_raion',
 'sport_objects_raion',
 'additional_education_raion',
 'culture_objects_top_25',
 'culture_objects_top_25_raion',
 'shopping_centers_raion',
 'office_raion',
 'thermal_power_plant_raion',
 'incineration_raion',
 'oil_chemistry_raion',
 'radiation_raion',
 'railroad_terminal_raion',
 'big_market_raion',
 'nuclear_reactor_raion',
 'detention_facility_raion',
 'full_all',
 'male_f',
 'female_f',
 'young_all',
 'young_male',
 'young_female',
 'work_all',
 'work_male',
 'work_female',
 'ekder_all',
 'ekder_male',
 'ekder_female',
 '0_6_all',
 '0_6_male',
 '0_6_female',
 '7_14_all',
 '7_14_male',
 '7_14_female',
 '0_17_all',
 '0_17_male',
 '0_17_female',
 '16_29_all',
 '16_29_male',
 '16_29_female',
 '0_13_all',
 '0_13_male',
 '0_13_female',
 'raion_build_count_with_material_info',
 'build_count_block',
 'build_count_wood',
 'build_count_frame',
 'build_count_brick',
 'build_count_monolith',
 'build_count_panel',
 'build_count_foam',
 'build_count_slag',
 'build_count_mix',
 'raion_build_count_with_builddate_info',
 'build_count_before_1920',
 'build_count_1921-1945',
 'build_count_1946-1970',
 'build_count_1971-1995',
 'build_count_after_1995',
 'ID_metro',
 'metro_min_avto',
 'metro_km_avto',
 'metro_min_walk',
 'metro_km_walk',
 'kindergarten_km',
 'school_km',
 'park_km',
 'green_zone_km',
 'industrial_km',
 'water_treatment_km',
 'cemetery_km',
 'incineration_km',
 'railroad_station_walk_km',
 'railroad_station_walk_min',
 'ID_railroad_station_walk',
 'railroad_station_avto_km',
 'railroad_station_avto_min',
 'ID_railroad_station_avto',
 'public_transport_station_km',
 'public_transport_station_min_walk',
 'water_km',
 'water_1line',
 'mkad_km',
 'ttk_km',
 'sadovoe_km',
 'bulvar_ring_km',
 'kremlin_km',
 'big_road1_km',
 'ID_big_road1',
 'big_road1_1line',
 'big_road2_km',
 'ID_big_road2',
 'railroad_km',
 'railroad_1line',
 'zd_vokzaly_avto_km',
 'ID_railroad_terminal',
 'bus_terminal_avto_km',
 'ID_bus_terminal',
 'oil_chemistry_km',
 'nuclear_reactor_km',
 'radiation_km',
 'power_transmission_line_km',
 'thermal_power_plant_km',
 'ts_km',
 'big_market_km',
 'market_shop_km',
 'fitness_km',
 'swim_pool_km',
 'ice_rink_km',
 'stadium_km',
 'basketball_km',
 'hospice_morgue_km',
 'detention_facility_km',
 'public_healthcare_km',
 'university_km',
 'workplaces_km',
 'shopping_centers_km',
 'office_km',
 'additional_education_km',
 'preschool_km',
 'big_church_km',
 'church_synagogue_km',
 'mosque_km',
 'theater_km',
 'museum_km',
 'exhibition_km',
 'catering_km',
 'ecology',
 'green_part_500',
 'prom_part_500',
 'office_count_500',
 'office_sqm_500',
 'trc_count_500',
 'trc_sqm_500',
 'cafe_count_500',
 'cafe_sum_500_min_price_avg',
 'cafe_sum_500_max_price_avg',
 'cafe_avg_price_500',
 'cafe_count_500_na_price',
 'cafe_count_500_price_500',
 'cafe_count_500_price_1000',
 'cafe_count_500_price_1500',
 'cafe_count_500_price_2500',
 'cafe_count_500_price_4000',
 'cafe_count_500_price_high',
 'big_church_count_500',
 'church_count_500',
 'mosque_count_500',
 'leisure_count_500',
 'sport_count_500',
 'market_count_500',
 'green_part_1000',
 'prom_part_1000',
 'office_count_1000',
 'office_sqm_1000',
 'trc_count_1000',
 'trc_sqm_1000',
 'cafe_count_1000',
 'cafe_sum_1000_min_price_avg',
 'cafe_sum_1000_max_price_avg',
 'cafe_avg_price_1000',
 'cafe_count_1000_na_price',
 'cafe_count_1000_price_500',
 'cafe_count_1000_price_1000',
 'cafe_count_1000_price_1500',
 'cafe_count_1000_price_2500',
 'cafe_count_1000_price_4000',
 'cafe_count_1000_price_high',
 'big_church_count_1000',
 'church_count_1000',
 'mosque_count_1000',
 'leisure_count_1000',
 'sport_count_1000',
 'market_count_1000',
 'green_part_1500',
 'prom_part_1500',
 'office_count_1500',
 'office_sqm_1500',
 'trc_count_1500',
 'trc_sqm_1500',
 'cafe_count_1500',
 'cafe_sum_1500_min_price_avg',
 'cafe_sum_1500_max_price_avg',
 'cafe_avg_price_1500',
 'cafe_count_1500_na_price',
 'cafe_count_1500_price_500',
 'cafe_count_1500_price_1000',
 'cafe_count_1500_price_1500',
 'cafe_count_1500_price_2500',
 'cafe_count_1500_price_4000',
 'cafe_count_1500_price_high',
 'big_church_count_1500',
 'church_count_1500',
 'mosque_count_1500',
 'leisure_count_1500',
 'sport_count_1500',
 'market_count_1500',
 'green_part_2000',
 'prom_part_2000',
 'office_count_2000',
 'office_sqm_2000',
 'trc_count_2000',
 'trc_sqm_2000',
 'cafe_count_2000',
 'cafe_sum_2000_min_price_avg',
 'cafe_sum_2000_max_price_avg',
 'cafe_avg_price_2000',
 'cafe_count_2000_na_price',
 'cafe_count_2000_price_500',
 'cafe_count_2000_price_1000',
 'cafe_count_2000_price_1500',
 'cafe_count_2000_price_2500',
 'cafe_count_2000_price_4000',
 'cafe_count_2000_price_high',
 'big_church_count_2000',
 'church_count_2000',
 'mosque_count_2000',
 'leisure_count_2000',
 'sport_count_2000',
 'market_count_2000',
 'green_part_3000',
 'prom_part_3000',
 'office_count_3000',
 'office_sqm_3000',
 'trc_count_3000',
 'trc_sqm_3000',
 'cafe_count_3000',
 'cafe_sum_3000_min_price_avg',
 'cafe_sum_3000_max_price_avg',
 'cafe_avg_price_3000',
 'cafe_count_3000_na_price',
 'cafe_count_3000_price_500',
 'cafe_count_3000_price_1000',
 'cafe_count_3000_price_1500',
 'cafe_count_3000_price_2500',
 'cafe_count_3000_price_4000',
 'cafe_count_3000_price_high',
 'big_church_count_3000',
 'church_count_3000',
 'mosque_count_3000',
 'leisure_count_3000',
 'sport_count_3000',
 'market_count_3000',
 'green_part_5000',
 'prom_part_5000',
 'office_count_5000',
 'office_sqm_5000',
 'trc_count_5000',
 'trc_sqm_5000',
 'cafe_count_5000',
 'cafe_sum_5000_min_price_avg',
 'cafe_sum_5000_max_price_avg',
 'cafe_avg_price_5000',
 'cafe_count_5000_na_price',
 'cafe_count_5000_price_500',
 'cafe_count_5000_price_1000',
 'cafe_count_5000_price_1500',
 'cafe_count_5000_price_2500',
 'cafe_count_5000_price_4000',
 'cafe_count_5000_price_high',
 'big_church_count_5000',
 'church_count_5000',
 'mosque_count_5000',
 'leisure_count_5000',
 'sport_count_5000',
 'market_count_5000',
 'price_doc']

In [ ]:
# Перемещение String-столбцов в одну группу:
cols = data.columns.tolist()
cols = cols[9:11] + cols[27:28] + cols[31:39] + cols[104:105] + cols[112:113] + cols[116:117] + cols[150:151] + cols[:9] + cols[11:27] + cols[28:31] + cols[39:104] + cols[105:112] + cols[113:116] + cols[117:150] + cols[151:]
data = data[cols]
data

        product_type            sub_area  ... market_count_5000 price_doc
8056      Investment           Hamovniki  ...                10   2750000
8154      Investment     Severnoe Butovo  ...                 3   7100000
8287      Investment           Ajeroport  ...                12  11700000
8387      Investment  Horoshevo-Mnevniki  ...                 7  10400000
8391      Investment             Ramenki  ...                 5   6200000
...              ...                 ...  ...               ...       ...
30462  OwnerOccupier      Filevskij Park  ...                 7  10544070
30463     Investment    Severnoe Tushino  ...                 6  12000000
30467     Investment            Tverskoe  ...                15  25000000
30469     Investment        Obruchevskoe  ...                 7  13500000
30470     Investment         Novogireevo  ...                10   5600000

[6042 rows x 290 columns]

In [ ]:
# Кодирование столбцов с String-значениями
subdata = data.iloc[:, :15]

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
subdata_encoded = subdata.apply(le.fit_transform)

In [ ]:
subdata_encoded

       product_type  sub_area  ...  railroad_1line  ecology
8056              0        18  ...               0        0
8154              0        60  ...               0        1
8287              0         0  ...               0        3
8387              0        19  ...               0        3
8391              0        55  ...               0        4
...             ...       ...  ...             ...      ...
30462             1        15  ...               1        4
30463             0        61  ...               0        4
30467             0        71  ...               0        3
30469             0        46  ...               0        4
30470             0        45  ...               0        3

[6042 rows x 15 columns]

In [ ]:
subdata_2 = data.iloc[:, 15:]

In [ ]:
subdata_2

       full_sq  life_sq  floor  ...  sport_count_5000  market_count_5000  price_doc
8056        11     11.0    2.0  ...               161                 10    2750000
8154        45     27.0    6.0  ...                19                  3    7100000
8287        77     50.0    3.0  ...               146                 12   11700000
8387        56     29.0    5.0  ...               121                  7   10400000
8391        31     21.0    5.0  ...                93                  5    6200000
...        ...      ...    ...  ...               ...                ...        ...
30462       47     30.0   23.0  ...               123                  7   10544070
30463       56     29.0   13.0  ...                53                  6   12000000
30467       86     59.0    3.0  ...               171                 15   25000000
30469       64     32.0    5.0  ...                65                  7   13500000
30470       43     28.0    1.0  ...                54                 10    5600000

[6042 rows x 275 columns]

In [ ]:
subdata_encoded.reset_index(drop=True, inplace=True)
subdata_2.reset_index(drop=True, inplace=True)
data_2 = pd.concat([subdata_encoded, subdata_2], axis = 1)

In [ ]:
data_2

      product_type  sub_area  ...  market_count_5000  price_doc
0                0        18  ...                 10    2750000
1                0        60  ...                  3    7100000
2                0         0  ...                 12   11700000
3                0        19  ...                  7   10400000
4                0        55  ...                  5    6200000
...            ...       ...  ...                ...        ...
6037             1        15  ...                  7   10544070
6038             0        61  ...                  6   12000000
6039             0        71  ...                 15   25000000
6040             0        46  ...                  7   13500000
6041             0        45  ...                 10    5600000

[6042 rows x 290 columns]

Нормировка данных так, чтобы среднее = 0, стандартное отклонение = 1

In [ ]:
# Среднее значение
mymean = data_2.mean(axis=0)
# Стандартное отклонение
mystd = data_2.std(axis=0)
data_2 -= mymean
data_2 /= mystd
data_2

      product_type  sub_area  ...  market_count_5000  price_doc
0        -0.243407 -0.904369  ...           0.230040  -0.955894
1        -0.243407  0.886709  ...          -1.445403  -0.262920
2        -0.243407 -1.671973  ...           0.708737   0.469881
3        -0.243407 -0.861724  ...          -0.488007   0.262785
4        -0.243407  0.673486  ...          -0.966705  -0.406294
...            ...       ...  ...                ...        ...
6037      4.107669 -1.032303  ...          -0.488007   0.285736
6038     -0.243407  0.929354  ...          -0.727356   0.517672
6039     -0.243407  1.355801  ...           1.426784   2.588629
6040     -0.243407  0.289683  ...          -0.488007   0.756629
6041     -0.243407  0.247039  ...           0.230040  -0.501876

[6042 rows x 290 columns]

In [ ]:
data_2 = data_2.drop(columns=['incineration_raion'])
data_2

      product_type  sub_area  ...  market_count_5000  price_doc
0        -0.243407 -0.904369  ...           0.230040  -0.955894
1        -0.243407  0.886709  ...          -1.445403  -0.262920
2        -0.243407 -1.671973  ...           0.708737   0.469881
3        -0.243407 -0.861724  ...          -0.488007   0.262785
4        -0.243407  0.673486  ...          -0.966705  -0.406294
...            ...       ...  ...                ...        ...
6037      4.107669 -1.032303  ...          -0.488007   0.285736
6038     -0.243407  0.929354  ...          -0.727356   0.517672
6039     -0.243407  1.355801  ...           1.426784   2.588629
6040     -0.243407  0.289683  ...          -0.488007   0.756629
6041     -0.243407  0.247039  ...           0.230040  -0.501876

[6042 rows x 289 columns]

In [ ]:
data_2.describe()

       product_type      sub_area  ...  market_count_5000     price_doc
count  6.042000e+03  6.042000e+03  ...       6.042000e+03  6.042000e+03
mean   2.519078e-15 -8.039562e-17  ...      -1.384931e-16 -2.886727e-17
std    1.000000e+00  1.000000e+00  ...       1.000000e+00  1.000000e+00
min   -2.434068e-01 -1.671973e+00  ...      -2.163449e+00 -1.314329e+00
25%   -2.434068e-01 -9.043686e-01  ...      -9.667049e-01 -4.700155e-01
50%   -2.434068e-01 -8.829615e-03  ...       2.300396e-01 -2.151284e-01
75%   -2.434068e-01  9.293541e-01  ...       7.087373e-01  2.787153e-01
max    4.107669e+00  1.696959e+00  ...       2.623528e+00  1.375945e+01

[8 rows x 289 columns]

In [ ]:
ydata = data_2.iloc[:, 288]

In [ ]:
ydata

0      -0.955894
1      -0.262920
2       0.469881
3       0.262785
4      -0.406294
          ...
6037    0.285736
6038    0.517672
6039    2.588629
6040    0.756629
6041   -0.501876
Name: price_doc, Length: 6042, dtype: float64

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_2, ydata, test_size=0.33, random_state=42)

In [ ]:
!pip install -q -U keras-tuner

In [ ]:
%tensorflow_version 2.x
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras import utils
from google.colab import files
from kerastuner.tuners import RandomSearch, Hyperband, BayesianOptimization
import numpy as np

# Модель 1 - 3 слоя, (128, 64, 32) нейронов в слоях соответственно
def build_model1(hp):
  model = Sequential()

  model.add(Dense(units=hp.Int('units_input', 
    min_value=128,
    max_value=128,
    step=32), input_shape=(X_train.shape[1],), activation='relu'))
  
  model.add(Dense(units=hp.Int('units_hidden', min_value=64, max_value=64, step=32), activation='relu'))
  model.add(Dense(units=hp.Int('units_hidden', min_value=32, max_value=32, step=32), activation='relu'))

  model.compile(optimizer="adam", loss='mse', metrics=['mae'])
  
  return model

# Модель 2 - 3 слоя, (32, 64, 128) нейронов в слоях соответственно
def build_model2(hp):
  model = Sequential()

  model.add(Dense(units=hp.Int('units_input', 
    min_value=32,
    max_value=32,
    step=32), input_shape=(X_train.shape[1],), activation='relu'))
  
  model.add(Dense(units=hp.Int('units_hidden', min_value=64, max_value=64, step=32), activation='relu'))
  model.add(Dense(units=hp.Int('units_hidden', min_value=128, max_value=128, step=32), activation='relu'))

  model.compile(optimizer="adam", loss='mse', metrics=['mae'])
  
  return model

# Модель 3 - 2 слоя, по 64 нейрона в слоях
def build_model3(hp):
  model = Sequential()

  model.add(Dense(units=hp.Int('units_input',
    min_value=64, 
    max_value=64,
    step=32), input_shape=(X_train.shape[1],), activation='relu'))
  
  model.add(Dense(units=hp.Int('units_hidden', min_value=64, max_value=64, step=32), activation='relu'))

  model.compile(optimizer="adam", loss='mse', metrics=['mae'])
  
  return model

tuner1 = BayesianOptimization(
  build_model1, # функция создания модели
  objective ='val_mae', # метрика, которую нужно оптимизировать
  max_trials = 5, # максимальное количество запусков обучения
  directory = 'test_directory1' # каталог, куда сохраняются обученные сети
)

tuner2 = BayesianOptimization(
  build_model2,
  objective ='val_mae',
  max_trials = 5,
  directory = 'test_directory2'
)

tuner3 = BayesianOptimization(
  build_model3,
  objective ='val_mae',
  max_trials = 5,
  directory = 'test_directory3'
)

INFO:tensorflow:Reloading Oracle from existing project test_directory1/untitled_project/oracle.json
INFO:tensorflow:Reloading Tuner from test_directory1/untitled_project/tuner0.json
INFO:tensorflow:Reloading Oracle from existing project test_directory2/untitled_project/oracle.json
INFO:tensorflow:Reloading Tuner from test_directory2/untitled_project/tuner0.json
INFO:tensorflow:Reloading Oracle from existing project test_directory3/untitled_project/oracle.json
INFO:tensorflow:Reloading Tuner from test_directory3/untitled_project/tuner0.json

In [ ]:
tuner1.search(X_train, # Данные для обучения
             y_train, # Данные для обучения
             batch_size=32, # Размер мини-выборки
             epochs=10, # Количество эпох обучения
             validation_split=0.2, # Часть данных, которая будет использоваться для проверки
            verbose=1,)

INFO:tensorflow:Oracle triggered exit

In [ ]:
tuner1.search_space_summary()

Search space summary
Default search space size: 2
units_input (Int)
{'default': None, 'conditions': [], 'min_value': 128, 'max_value': 128, 'step': 32, 'sampling': None}
units_hidden (Int)
{'default': None, 'conditions': [], 'min_value': 64, 'max_value': 64, 'step': 32, 'sampling': None}

In [ ]:
tuner1.results_summary()

Results summary
Results in test_directory1/untitled_project
Showing 10 best trials
Objective(name='val_mae', direction='min')
Trial summary
Hyperparameters:
units_input: 128
units_hidden: 64
Score: 0.4111044406890869

In [ ]:
models1 = tuner1.get_best_models(num_models=3)

In [ ]:
for model in models1:
  model.summary()
  model.evaluate(X_test, y_test)
  print()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 128)               37120
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160
=================================================================
Total params: 49,536
Trainable params: 49,536
Non-trainable params: 0
_________________________________________________________________
63/63 [==============================] - 0s 1ms/step - loss: 0.3605 - mae: 0.4087

In [ ]:
tuner2.search(X_train, # Данные для обучения
             y_train, # Данные для обучения
             batch_size=32, # Размер мини-выборки
             epochs=10, # Количество эпох обучения
             validation_split=0.2, # Часть данных, которая будет использоваться для проверки
            verbose=1,)

INFO:tensorflow:Oracle triggered exit

In [ ]:
tuner2.search_space_summary()

Search space summary
Default search space size: 2
units_input (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 32, 'step': 32, 'sampling': None}
units_hidden (Int)
{'default': None, 'conditions': [], 'min_value': 64, 'max_value': 64, 'step': 32, 'sampling': None}

In [ ]:
tuner2.results_summary()

Results summary
Results in test_directory2/untitled_project
Showing 10 best trials
Objective(name='val_mae', direction='min')
Trial summary
Hyperparameters:
units_input: 32
units_hidden: 64
Score: 0.41149818897247314

In [ ]:
models2 = tuner2.get_best_models(num_models=3)

WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

In [ ]:
for model in models2:
  model.summary()
  model.evaluate(X_test, y_test)
  print()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 32)                9280
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160
=================================================================
Total params: 15,552
Trainable params: 15,552
Non-trainable params: 0
_________________________________________________________________
63/63 [==============================] - 0s 1ms/step - loss: 0.3229 - mae: 0.4065

In [ ]:
tuner3.search(X_train, # Данные для обучения
             y_train, # Данные для обучения
             batch_size=32, # Размер мини-выборки
             epochs=10, # Количество эпох обучения
             validation_split=0.2, # Часть данных, которая будет использоваться для проверки
            verbose=1,)

INFO:tensorflow:Oracle triggered exit

In [ ]:
tuner3.search_space_summary()

Search space summary
Default search space size: 2
units_input (Int)
{'default': None, 'conditions': [], 'min_value': 64, 'max_value': 64, 'step': 32, 'sampling': None}
units_hidden (Int)
{'default': None, 'conditions': [], 'min_value': 64, 'max_value': 64, 'step': 32, 'sampling': None}

In [ ]:
tuner3.results_summary()

Results summary
Results in test_directory3/untitled_project
Showing 10 best trials
Objective(name='val_mae', direction='min')
Trial summary
Hyperparameters:
units_input: 64
units_hidden: 64
Score: 0.4309755265712738

In [ ]:
models3 = tuner3.get_best_models(num_models=3)

WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

In [ ]:
for model in models3:
  model.summary()
  model.evaluate(X_test, y_test)
  print()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 64)                18560
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160
=================================================================
Total params: 22,720
Trainable params: 22,720
Non-trainable params: 0
_________________________________________________________________
63/63 [==============================] - 0s 1ms/step - loss: 0.3706 - mae: 0.4294

In [ ]:
# Корреляция для первой модели:
model = Sequential()
model.add(Dense(128, input_shape=(X_train.shape[1],), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/10
102/102 [==============================] - 1s 5ms/step - loss: 0.8393 - mae: 0.6115 - val_loss: 0.7217 - val_mae: 0.5529
Epoch 2/10
102/102 [==============================] - 0s 2ms/step - loss: 0.4999 - mae: 0.5096 - val_loss: 0.4834 - val_mae: 0.4809
Epoch 3/10
102/102 [==============================] - 0s 2ms/step - loss: 0.3798 - mae: 0.4621 - val_loss: 0.4811 - val_mae: 0.4798
Epoch 4/10
102/102 [==============================] - 0s 3ms/step - loss: 0.3444 - mae: 0.4436 - val_loss: 0.3822 - val_mae: 0.4406
Epoch 5/10
102/102 [==============================] - 0s 3ms/step - loss: 0.3182 - mae: 0.4285 - val_loss: 0.3723 - val_mae: 0.4337
Epoch 6/10
102/102 [==============================] - 0s 2ms/step - loss: 0.3186 - mae: 0.4234 - val_loss: 0.3294 - val_mae: 0.4083
Epoch 7/10
102/102 [==============================] - 0s 2ms/step - loss: 0.3044 - mae: 0.4103 - val_loss: 0.3188 - val_mae: 0.4005
Epoch 8/10
102/102 [==============================] - 0s 2ms/step - loss: 0.2846 - mae: 0.3928 - val_loss: 0.3089 - val_mae: 0.3952
Epoch 9/10
102/102 [==============================] - 0s 3ms/step - loss: 0.2830 - mae: 0.3901 - val_loss: 0.2981 - val_mae: 0.3869
Epoch 10/10
102/102 [==============================] - 0s 3ms/step - loss: 0.2825 - mae: 0.3876 - val_loss: 0.2991 - val_mae: 0.3959

In [ ]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_2 (Dense)              (None, 128)               37120
_________________________________________________________________
dense_3 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080
=================================================================
Total params: 47,456
Trainable params: 47,456
Non-trainable params: 0
_________________________________________________________________
None

In [ ]:
pred = model.predict(X_test)

In [ ]:
vec = np.array([])
for i in np.arange(0, len(pred)):
  vec = np.append(vec, pred[i][0])
vec

array([0.01319507, 0.        , 0.        , ..., 0.        , 0.12829664,
       0.        ])

In [ ]:
СС_tuner = np.corrcoef(vec, y_test)
СС_tuner = СС_tuner[0][1]
print(f'Коэффициент корреляции с истинными данными: {СС_tuner}')

Коэффициент корреляции с истинными данными: 0.9129703600724597